# Generated by Django 4.1 on 2023-05-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chest",
            fields=[
                ("chest_x_ray_id", models.AutoField(primary_key=True, serialize=False)),
                ("patient_id", models.IntegerField()),
                ("x_ray_id", models.IntegerField()),
                ("disease", models.BigIntegerField()),
            ],
        ),
    ]
